
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name:  loki-s3-secret
  namespace: loki
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # name of the generated secret
    name: loki-s3-secret
  data:
  - secretKey: access-key # Name of the element in the generated secret
    remoteRef:
      key: ceph/s3/k3s-loki-user  # The path of the secret, relative from the secrets path
      property: access-key  # name of the attribute to access
  - secretKey: secret-key
    remoteRef:
      key: ceph/s3/k3s-loki-user
      property: secret-key
