apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: vault
spec:
  provider:
    vault:
      server: "https://vault.homelab.kbushby.com:8200"
      # caBundle needed if vault TLS is signed using a custom CA.
      # If Vault TLS is valid signed by Letsencrypt this is not needed?
      # ca cert base64 encoded and remobed '\n' characteres"
      # <vault-ca> =`cat vault-ca.pem | base64 | tr -d "\n"`
      # caBundle: <vault-ca>
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
