apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-kube-pi-token
  namespace: external-dns
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # name of the generated secret
    name: external-dns-kube-pi-secret
  data:
  - secretKey: ddns-key # Name of the element in the generated secret
    remoteRef:
      key: external-dns-kube-pi  # The path of the secret, relative from the secrets path
      property: key  # name of the attribute to access
