apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: ceph-s3-dev
  namespace: rook-ceph
# This endpoint in this section needs is an endpoint from the master zone  in the master zone group of realm-a. See object-multisite.md for more details.
spec:
  pull: