replicaCount: 3
k8sAppLabelOverride: kube-dns
serviceAccount:
  create: true
service:
  name: kube-dns
  clusterIP: 10.43.0.10

# Default zone is what Kubernetes recommends:
# https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
servers:
- zones:
  - zone: .
  port: 53
  plugins:
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  # Required to query kubernetes API for data
  - name: kubernetes
    parameters: cluster.local in-addr.arpa ip6.arpa
    configBlock: |-
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
  - name: hosts
    parameters: /etc/coredns/NodeHosts
    configBlock: |-
      ttl 60
      reload 15s
      fallthrough
    
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: cache
    parameters: 30
  - name: loop
  - name: reload
  - name: loadbalance
  - name: import
    parameters: /etc/coredns/custom/*.override
  - name: forward
    parameters: homelab.kbushby.com 192.168.20.2
  - name: forward
    parameters: . /etc/resolv.conf


# When using preexisting k3s CoreDNS instance add the following to the exising
# ServiceAccount: coredns
# ConfigMap:      coredns
# Service:        kube-dns
# Deployment      coredns

###
# annotations:
#    meta.helm.sh/release-name: coredns
#    meta.helm.sh/release-namespace: kube-system

# labels:
#    app.kubernetes.io/managed-by: Helm


# helm upgrade --install coredns coredns/coredns --namespace=kube-system -f coredns-values.yaml --history-max=3
# helm uninstall coredns -n kube-system