
controller:
  image:
    pullPolicy: IfNotPresent

  # Pod disruption budget ensures availability during updates
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  # Install recommended plugins during setup
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - job-dsl:latest
    - blueocean:latest
    - credentials-binding:latest
  
  additionalPlugins:
    - github:latest
    - maven-plugin:latest
    - pipeline-graph-view:latest
    - pipeline-model-definition:latest
    - pipeline-stage-view:latest
    - pipeline-utility-steps:latest
    - oic-auth:latest
    - cloudbees-folder:latest
    - coverage:latest

  # Environment variables
  containerEnv:
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: jenkins-oidc-secret
          key: secret

  # Enable Jenkins Configuration as Code
  JCasC:
    enabled: true
    defaultConfig: true
    securityRealm : |-
      oic:
        serverConfiguration:
          manual:
            authorizationServerUrl: https://iam.homelab.kbushby.com/realms/master/protocol/openid-connect/auth
            endSessionUrl: https://iam.homelab.kbushby.com/realms/master/protocol/openid-connect/logout
            jwksServerUrl: https://iam.homelab.kbushby.com/realms/master/protocol/openid-connect/certs
            tokenAuthMethod: client_secret_basic
            tokenServerUrl: https://iam.homelab.kbushby.com/realms/master/protocol/openid-connect/token
            scopes: "openid profile email groups"
            userInfoServerUrl: https://iam.homelab.kbushby.com/realms/master/protocol/openid-connect/userinfo
            useRefreshTokens: true
            issuer: https://iam.homelab.kbushby.com/realms/master
        # Credentials
        clientId: "jenkins-oidc"
        clientSecret: "${OIDC_CLIENT_SECRET}"
        # Claims
        userNameField: "preferred_username"
        userIdStrategy: "caseSensitive"
        fullNameFieldName: "preferred_username"
        emailFieldName: "email"
        groupsFieldName: "groups"
        groupIdStrategy: "caseSensitive"
        # Additional Config
        logoutFromOpenidProvider: true
        postLogoutRedirectUrl: "https://iam.homelab.kbushby.com/realms/master/.well-known/openid-configuration"
        # Security
        disableSslVerification: false
        
  sidecars:
    configAutoReload:
      logging:
        configuration:
          override: true
          logLevel: WARN

  # -- Resource allocation (Requests and Limits)
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
    # ExternalDNS entry
      external-dns.alpha.kubernetes.io/hostname: jenkins.homelab.kbushby.com
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: cloudflare-ca-issuer
      cert-manager.io/common-name: jenkins.homelab.kbushby.com
    path: /
    pathType: Prefix
    hostName: jenkins.homelab.kbushby.com
    tls:
      - hosts:
        - jenkins.homelab.kbushby.com
        secretName: jenkins-tls

# Persistent storage for Jenkins home directory
persistence:
  enabled: true
  # Use existing claim
  existingClaim: jenkins-pv-claim 
  # storageClass: rook-ceph-block  # Leave empty to use default storage class
  # size: "20Gi"
  # accessMode: ReadWriteOnce

# TODO: Review Paramater options and fix
# Jenkins agent configuration
agent:
  enabled: true
  # Default agent pod template
  podTemplates:
    default: |
      - name: default
        label: jenkins-agent
        serviceAccount: jenkins
        containers:
          - name: jnlp
            image: jenkins/inbound-agent:latest
            resourceRequestCpu: "50m"
            resourceRequestMemory: "128Mi"
            resourceLimitCpu: "1000m"
            resourceLimitMemory: "1Gi"


# Service account for Jenkins
# manifest file in the repo isn't used for now
serviceAccount:
  create: true
  name: jenkins


# helm upgrade --install jenkins jenkins/jenkins --namespace jenkins -f jenkins-values.yaml --history-max=3
# helm uninstall jenkins -n jenkins

# kubectl get secret -n jenkins jenkins -o=jsonpath='{.data.jenkins-admin-password}' | base64 --decode; echo