
#nodeSelector: {
  # exclude GPU nodes
#}
#tolerations: []

monitoring:
  # Enabled Prometheus logging
  enabled: true


# Allow the operator to run on control-plane nodes if needed
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule


# helm upgrade --install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph -f rook-ceph-operator-values.yaml --history-max=3
# for CRD in $(kubectl get crd | awk '/ceph.rook.io/ {print $1}'); do     kubectl get -n rook-ceph "$CRD" -o name |     xargs -I {} kubectl patch -n rook-ceph {} --type merge -p '{"metadata":{"finalizers": []}}'; done
# kubectl delete -f https://raw.githubusercontent.com/rook/rook/v1.19.3/deploy/examples/crds.yaml --ignore-not-found
