---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "nginx-ingress-pool"
  namespace: kube-system
spec:
  blocks:
    # 	192.168.24.1 - 192.168.24.254
    #   255 Hosts
    - cidr: "192.168.24.0/24"
---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "dev-lb-pool"
  namespace: kube-system
spec:
  blocks:
    #   192.168.25.1 - 192.168.25.254
    #   255 Hosts
    - cidr: "192.168.25.0/24"
  # serviceSelector:
  #   matchLabels:
  #     environment: "development"
---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "prod-lb-pool"
  namespace: kube-system
spec:
  blocks:
    #   192.168.26.1 - 192.168.26.254
    #   255 Hosts
    - cidr: "192.168.26.0/24"
  # serviceSelector:
  #   matchLabels:
  #     environment: "production"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
  namespace: kube-system
spec:
  interfaces:
    - "^eno[0-9]+"
  externalIPs: true
  loadBalancerIPs: true
