apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
type: kubernetes.io/basic-auth
data:
    username: YWRtaW4=
    password: TWluaXRlbmRvbjEyMw==
# echo -n 'Password123' | base64
# echo -n 'Password123' | base64 --decode
