# Creates a user with SCRAM-SHA-512 authentication
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: app-producer
  namespace: kafka
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Allow producing to user-events topic
      - resource:
          type: topic
          name: demo-topic
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
      # Required when the producer has idempotence enabled
      - resource:
          type: cluster
          name: dev-cluster
        operations:
          - IdempotentWrite
        host: "*"

---

# Creates a user with SCRAM-SHA-512 authentication
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: app-consumer
  namespace: kafka
  labels:
    strimzi.io/cluster: dev-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Allow producing to user-events topic
      - resource:
          type: topic
          name: demo-topic
          patternType: literal
        operations:
          - Read
          - Describe
      # Required when the producer has idempotence enabled
      - resource:
          type: cluster
          name: dev-cluster
        operations:
          - IdempotentWrite

# kubectl get secret app-producer -o jsonpath='{.data.password}' -n kafka | base64 -d;echo
# kubectl get secret app-consumer -o jsonpath='{.data.password}' -n kafka | base64 -d;echo
