apiVersion: v1
kind: Pod
metadata:
  name: netshoot-pod
  labels:
    app: netshoot

spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
      requests:
        memory: 128Mi
        cpu: 100m


#kubectl exec -it netshoot-pod -c netshoot -- /bin/bash
