apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: singlepool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1

# https://rook.io/docs/rook/v1.20/CRDs/Block-Storage/ceph-block-pool-crd/