apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: kafka
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      # Broker-level metrics
      - pattern: "kafka.server<type=BrokerTopicMetrics, name=(MessagesInPerSec|BytesInPerSec|BytesOutPerSec)><>(Count)"
        name: "kafka_server_broker_topic_metrics_$1_total"
        type: COUNTER
      # Partition-level metrics
      - pattern: "kafka.log<type=Log, name=Size, topic=(.+), partition=(.+)><>Value"
        name: "kafka_log_size"
        labels:
          topic: "$1"
          partition: "$2"