apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-oidc-secret
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # name of the generated secret
    name: oauth2-proxy-oidc-secret
  data:
  - secretKey: secret # Name of the element in the generated secret
    remoteRef:
      key: oidc/oauth2-proxy  # The path of the secret, relative from the secrets path
      property: secret  # name of the attribute to access
  - secretKey: cookie-secret
    remoteRef:
      key: oidc/oauth2-proxy
      property: cookie-secret

# Cookie secret
# Create a new secret with the following command
# openssl rand -base64 32 | head -c 32 | base64

